#! /bin/bash

index=  proc=  yhindex=  fname=  fastq=  recursive=  zip=  

usage="$(basename "$0") -- map single-end data using bowtie2 and yaha
  -h  show help and exit
  -x  path to bowtie2 index
  -y  path to yaha index
  -p  number of cores to use
  -s  average insert size
  -n  sample name
  -q  fastq file containing reads
  -r  recursive (optional)
  -z  gzip fastq files (optional)"

if [ $# -eq 0 ]; then
  echo "$usage"
  exit 1
fi

while getopts :x:p:y:n:q:rzh opt; do
  case $opt in
    h)  echo "$usage"
        exit
        ;;
    x)  index=$OPTARG
        ;;
    p)  proc=$OPTARG
        ;;
    y)  yhindex=$OPTARG
        ;;
    n)  fname=$OPTARG
        ;;
    q)  fastq=$OPTARG
        ;;
    r)  recursive=true
        ;;
    z)  zip=true
        ;;
    :)  printf "missing argument for -%s\n" "$OPTARG" >&2
        echo "$usage" >&2
        exit 1
        ;;
    \?) printf "illegal option: -%s\n" "$OPTARG" >&2
        echo "$usage" >&2
        exit 1
        ;;
  esac
done
shift $((OPTIND - 1))

map () {
  echo "Mapping ${2}"
  bowtie2 --local --dovetail -p$proc --fr -q -R5 -N1 -x $index \
   -U $1 \
  | samblaster -e -u "${2}.umap.fastq" \
  | samtools view -b - > "${2}_unsort.bam"

  yaha -t $proc -x $yhindex -q "${2}.umap.fastq" -L 11 -H 2000 -M 15 -osh stdout \
  | samblaster -s "${2}.split.sam" > /dev/null

  echo "Converting to bam"
  samtools view -Sb@ $proc "${2}.split.sam" > "${2}.split.bam"
  rm "${2}.split.sam"

  echo "Sorting alignment"
  samtools sort -@ $proc "${2}_unsort.bam" "${2}"
  rm "${2}_unsort.bam"

  echo "Indexing alignment"
  samtools index "${2}.bam"

  if [ "$zip" == true ]; then
    echo "Zipping fastq files"
    gzip *.fastq
  fi
}

if [ "$recursive" == true ]; then
  for directory in ./*; do
      if [ -d "$directory" ]; then
          cd $directory
          for fastq in $(ls -d *.fastq*);do
            fname=(${fastq//.fastq*/ })
            map $fastq $fname
          done
          cd ..
      fi
  done

else
  map
fi
