#! /usr/bin/env python

if __name__ == "__main__":
    from argparse import ArgumentParser
    import pkg_resources
    from tepy import tepy

    version = pkg_resources.require("TEpy")[0].version

    parser = ArgumentParser(description='TEpy -- discover polymorphic TE insertion and deletion sites')
    group = parser.add_mutually_exclusive_group()
    parser.add_argument('--version', action='version', version='%(prog)s '+str(version))
    parser.add_argument('-k', '--keep', help='keep all intermediate files', action='store_true', required=False, default=False)
    group.add_argument('-d', '--deletions', help='find deletions only', action='store_true', required=False, default=False)
    group.add_argument('-i', '--insertions', help='find insertions only', action='store_true', required=False, default=False)
    parser.add_argument('--strict', help='Report high-confidence variants only', required=False, default=False, action='store_true')
    parser.add_argument('--mask', help='Mask chromosomes, comma separated list', required=False, type=str, default='')
    parser.add_argument('-D', '--discordant', help='Supply discordant reads bam file', required=False, default=False)
    parser.add_argument('-p', '--proc', help='number of processors', required=False, default=1, type=int)
    parser.add_argument('-n', '--name', help='sample name', required=True)
    parser.add_argument('-c', '--conc', help='bam file from bowtie2', required=True)
    parser.add_argument('-s', '--split', help='split reads bam file from yaha', required=True)
    parser.add_argument('-t', '--te', help='TE annotation bedfile', required=True)
    options = parser.parse_args()

    tepy.discover(options)